nomen = [
    "Abenteuer", "Achtsamkeit", "Aktion", "Allianz", "Anfang", "Anker", "Anliegen",
    "Anpassung", "Antrieb", "Applaus", "Arbeitsplatz", "Aufbruch", "Aufgabe",
    "Aufklärung", "Aufruf", "Aussicht", "Authentizität", "Ausdauer", "Ausgleich",
    "Ausweg", "Balance", "Barrierefreiheit", "Bauernhof", "Bekenntnis", "Beteiligung",
    "Bewegung", "Bildung", "Biodiversität", "Blickwinkel", "Blütezeit", "Bodenständigkeit",
    "Botschaft", "Brückenbau", "Bündnis", "Bürgernähe", "Bürgerrecht", "Chance",
    "Charisma", "Charakter", "Chemie", "Chor", "Community", "Denkanstoß",
    "Demokratie", "Dialog", "Diversität", "Dynamik", "Durchblick", "Durchbruch",
    "Echtheit", "Effizienz", "Eigeninitiative", "Einsatz", "Energie", "Engagement",
    "Enthusiasmus", "Entfaltung", "Entlastung", "Entscheidung", "Entwicklung", "Epoche",
    "Erfolg", "Erfüllung", "Ergebnis", "Erlebnis", "Erneuerung", "Eröffnung",
    "Erreichbarkeit", "Erziehung", "Essenz", "Experiment", "Expertise", "Fairness",
    "Farbvielfalt", "Faszination", "Felder", "Feminismus", "Feuer", "Fokus",
    "Freiheit", "Freiheitsdrang", "Freiraum", "Freude", "Freundschaft", "Frieden",
    "Fundament", "Garten", "Geborgenheit", "Gedanke", "Gefühl", "Gelegenheit",
    "Gleichgewicht", "Glück", "Globalität", "Glühwürmchen", "Grenzenlosigkeit",
    "Greifbarkeit", "Grünfläche", "Grundsatz", "Gruppengeist", "Handlung", "Harmonie",
    "Herzenswärme", "Herzschlag", "Hintergrund", "Hoffnung", "Horizont", "Hunger",
    "Ideal", "Identität", "Idee", "Impuls", "Individualität", "Industrie",
    "Initiative", "Inklusion", "Innovation", "Inspiration", "Integrität", "Interaktion",
    "Intuition", "Investition", "Irritation", "Jahrhundert", "Jugend", "Kampfgeist",
    "Kapazität", "Karriere", "Kern", "Klima", "Klimaschutz", "Kompass",
    "Kompetenz", "Kompromiss", "Konsens", "Kontakt", "Kontinuität", "Kooperation",
    "Kraft", "Kreativität", "Kritik", "Kultur", "Kunst", "Lebendigkeit",
    "Lebensfreude", "Lebensgrundlage", "Lebensmittelpunkt", "Lebensqualität", "Leidenschaft",
    "Lernprozess", "Licht", "Liebenswürdigkeit", "Liebe", "Lösung", "Macht",
    "Magie", "Menschlichkeit", "Miteinander", "Mission", "Mitgefühl", "Mitspracherecht",
    "Modernität", "Möglichkeit", "Mut", "Nachbarschaft", "Nachhaltigkeit",
    "Nachklang", "Nachwuchs", "Natur", "Naturkraft", "Netzwerk", "Neubeginn",
    "Neugier", "Neutralität", "Offenheit", "Optimismus", "Orientierung", "Originalität",
    "Pfade", "Plan", "Plattform", "Potenzial", "Präsenz", "Prävention",
    "Privatsphäre", "Progressivität", "Projekt", "Protest", "Puls", "Qualität",
    "Raum", "Rebellion", "Recht", "Rechtsstaat", "Redlichkeit", "Reflexion",
    "Reform", "Regenbogen", "Resilienz", "Respekt", "Ressource", "Revolution",
    "Rhythmus", "Richtung", "Ruhe", "Ruf", "Schatten", "Schirm",
    "Schlüssel", "Schöpfung", "Schutz", "Sensibilität", "Sichtbarkeit", "Sicherheit",
    "Signal", "Sinn", "Solidarität", "Sommer", "Spannung", "Spiegel",
    "Spontaneität", "Sprache", "Stabilität", "Standpunkt", "Start", "Stärke",
    "Stimme", "Strategie", "Struktur", "Stück", "Symbol", "Sympathie",
    "Synergie", "Talent", "Takt", "Teilhabe", "Thema", "Tiefe",
    "Toleranz", "Tradition", "Traum", "Treue", "Umarmung", "Umfeld",
    "Umsetzung", "Umwelt", "Unabhängigkeit", "Unterschied", "Unterstützung",
    "Verantwortung", "Veränderung", "Verbundenheit", "Verlässlichkeit", "Verlockung",
    "Vermächtnis", "Vernetzung", "Vertrauen", "Verwirklichung", "Vision",
    "Vorbilder", "Vorfreude", "Vorgabe", "Vorsprung", "Votum", "Wachstum",
    "Wahrheit", "Wandel", "Weg", "Wege", "Weitsicht", "Welle",
    "Wert", "Wertschätzung", "Widerstand", "Wille", "Wind", "Wirklichkeit",
    "Wissen", "Wohlstand", "Wunder", "Würde", "Wurzeln", "Zeitgeist",
    "Ziel", "Zivilcourage", "Zuflucht", "Zukunft", "Zuneigung",
    "Zusammenhalt", "Zuverlässigkeit", "Zwischenraum", "Freiheitskampf", "Herzschlag",
    "Entfesselung", "Richtungswechsel", "Zündfunke", "Leuchtkraft", "Sonnenstrahl",
    "Frühlingswind", "Pioniergeist", "Wegbereiter", "Sturmkraft", "Hoffnungsschimmer",
    "Herzensprojekt", "Zukunftsbild", "Aufbruchstimmung", "Gemeinsinn", "Wertegemeinschaft"
]

adverbien = [
    "abermals", "absolut", "achtsam", "allgemein", "allein", "allzu",
    "angeblich", "angemessen", "angstfrei", "anständig", "ausdrücklich",
    "ausführlich", "ausnahmslos", "ausreichend", "außergewöhnlich",
    "authentisch", "bald", "barrierefrei", "bedingungslos", "begeistert",
    "beharrlich", "beherzt", "bekanntlich", "belastbar", "beliebig",
    "benutzerfreundlich", "berührend", "bescheiden", "besonderermaßen",
    "beständig", "bestens", "bewegend", "bewusst", "bildhaft",
    "billig", "blitzschnell", "bloß", "bodenständig", "bravourös",
    "breitgefächert", "brennend", "brillant", "chaotisch", "charaktervoll",
    "charmant", "deutlich", "dicht", "direkt", "diszipliniert",
    "doppelt", "dringend", "durchaus", "durchdringend", "durchgehend",
    "dynamisch", "echt", "effektiv", "effizient", "eigenständig",
    "ehrfürchtig", "ehrlich", "eifrig", "eindrucksvoll", "einfach",
    "eindeutig", "einfühlsam", "eingehend", "einheitlich", "einmalig",
    "einsatzbereit", "einsichtig", "einzigartig", "elastisch", "emotional",
    "empfindsam", "energiegeladen", "energisch", "engagiert",
    "entfesselnd", "entschlossen", "entwicklungsorientiert", "erfahren",
    "erfinderisch", "erfolgreich", "erfreulich", "erfüllt", "ergiebig",
    "erheblich", "erkennbar", "erleuchtend", "erstaunlich", "erwartungsvoll",
    "erweitert", "erwiesenermaßen", "exakt", "exklusiv", "experimentierfreudig",
    "explizit", "fachkundig", "faktisch", "fantasievoll", "federleicht",
    "feinfühlig", "felsenfest", "fern", "fest", "fieberhaft",
    "filigran", "finanziell", "flächendeckend", "flexibel",
    "flink", "fließend", "fokussiert", "folgend", "formvollendet",
    "fortlaufend", "fortschrittlich", "fraglos", "frei", "freilich",
    "freundlich", "friedlich", "frisch", "froh", "fruchtbar",
    "fulminant", "fundiert", "gefühlvoll", "gekonnt", "gemeinschaftlich",
    "gemütlich", "genau", "generationsübergreifend", "genial",
    "gepflegt", "gerecht", "gerne", "gesellig", "gesund",
    "getreu", "gewaltfrei", "gewissenhaft", "gewollt", "gigantisch",
    "glasklar", "glatt", "gleich", "gleichbleibend", "gleichzeitig",
    "glorreich", "glücklich", "gottseidank", "gründlich", "grenzenlos",
    "griffig", "großartig", "grundsätzlich", "gründlich", "gut",
    "halbwegs", "harmonisch", "hartnäckig", "hautnah", "heftig",
    "heilsam", "heimisch", "heiter", "heldenhaft", "herzlich",
    "herzerwärmend", "hilfreich", "himmelweit", "hintergründig",
    "historisch", "hochaktuell", "hochansteckend", "hochgradig",
    "hochinteressant", "hochkarätig", "hoffnungsvoll", "hürdenfrei",
    "ideal", "ideell", "identitätsstiftend", "illustriert",
    "immer", "immerhin", "implizit", "inbrünstig", "individuell",
    "informativ", "innig", "innovativ", "intensiv", "interaktiv",
    "interdisziplinär", "interessant", "international", "intuitiv",
    "irgendwann", "irgendwie", "ironisch", "jederzeit", "jenseits",
    "jugendlich", "juristisch", "just", "kaum", "kinderfreundlich",
    "klar", "klug", "kognitiv", "kollektiv", "konkret",
    "konsequent", "kontinuierlich", "konzentriert", "konstruktiv",
    "kontaktfreudig", "kostbar", "kraftvoll", "kreativ", "kritisch",
    "kurzfristig", "lachend", "langfristig", "lebendig", "leidenschaftlich",
    "leicht", "leise", "leistungsstark", "leserlich", "liebenswürdig",
    "liebevoll", "locker", "logisch", "lohnenswert", "löblich",
    "lückenlos", "lustig", "maßgeblich", "maßvoll", "menschlich",
    "merklich", "methodisch", "mild", "minimalistisch", "miteinander",
    "mitfühlend", "mittlerweile", "modern", "modisch", "moralisch",
    "motiviert", "mutig", "nachdrücklich", "nachhaltig", "nachsichtig",
    "nahbar", "namentlich", "natürlich", "nebenbei", "nebenwirkungsfrei",
    "niederschwellig", "nie", "niemals", "nirgendwo", "noch",
    "notwendig", "nüchtern", "nunmehr", "objektiv", "offensichtlich",
    "offiziell", "oftmals", "ohnegleichen", "ohneweiteres",
    "ordnungsgemäß", "originell", "partnerschaftlich", "passend",
    "persönlich", "phantasievoll", "plötzlich", "politisch", "potenziell",
    "praktisch", "prächtig", "präzise", "preiswert", "problemlos",
    "proaktiv", "professionell", "progressiv", "pünktlich", "radikal",
    "rasant", "realistisch", "rechtzeitig", "redegewandt", "regelmäßig",
    "reichhaltig", "reichlich", "reif", "rein", "relevant",
    "respektvoll", "richtig", "risikofrei", "risikofreudig",
    "robust", "romantisch", "routiniert", "ruckartig", "rücksichtsvoll",
    "ruhig", "rundherum", "rundum", "sanft", "scharfsinnig",
    "schlicht", "schlüssig", "schmerzlich", "schmucklos",
    "schnell", "schonend", "schön", "schriftlich", "schwungvoll",
    "sehenswert", "selbstbewusst", "selbstlos", "selbstverständlich",
    "selten", "sicherlich", "simpel", "sinnvoll", "sofort",
    "solide", "sonnenklar", "sozial", "spontan", "sportlich",
    "sprachlich", "spürbar", "stabil", "stark", "stattlich",
    "staunenswert", "stets", "stilvoll", "strahlend", "strategisch",
    "stressfrei", "strukturiert", "subtil", "symbolisch",
    "sympathisch", "tadellos", "taktvoll", "tapfer", "technisch",
    "teilweise", "thematisch", "theoretisch", "tief", "tolerant",
    "traditionell", "transparent", "treffend", "treu",
    "triumphal", "trotzdem", "überall", "überdurchschnittlich",
    "überhaupt", "überlegt", "überraschend", "überzeugend",
    "umfassend", "umgänglich", "umsetzbar", "unabhängig",
    "unanfechtbar", "unauffällig", "unaufhörlich", "unbedingt",
    "unbeschwert", "unbeugsam", "unbewusst", "ungewöhnlich",
    "ungezügelt", "ungezwungen", "unglaublich", "unkompliziert",
    "unmittelbar", "unmissverständlich", "unmöglich",
    "unparteiisch", "unproblematisch", "unschlagbar",
    "unschuldig", "unschätzbar", "unsererseits", "unübersehbar",
    "unverändert", "unverfälscht", "unvergänglich", "unvergleichlich",
    "unverhofft", "unvorhergesehen", "unweigerlich",
    "urplötzlich", "ursprünglich", "variabel", "verantwortungsvoll",
    "verbindlich", "verdächtig", "verfügbar", "vergnügt",
    "verhältnismäßig", "verlockend", "vermehrt", "vermutlich",
    "verrückt", "verschwenderisch", "versiert", "verständlich",
    "vertrauensvoll", "vielfach", "vielfältig", "virtuell",
    "visionär", "vital", "vollends", "vollständig", "vorbildlich",
    "vorerst", "vordergründig", "vorher", "vorhin", "vorzüglich",
    "wachsam", "warmherzig", "weitsichtig", "weitläufig",
    "wenigstens", "wertvoll", "wesentlich", "wichtig",
    "widerstandsfähig", "willkommen", "wissbegierig",
    "wohlerzogen", "wohlgemerkt", "wunderbar", "wunschgemäß",
    "wütend", "zaghaft", "zauberhaft", "zeitgemäß",
    "zeitnah", "zielgerichtet", "zielstrebig",
    "zügig", "zuverlässig", "zuvorkommend",
    "zweckmäßig", "zweifellos"
]

pronomen = [
    "ich", "du", "er", "sie", "es", "wir", "ihr", "sie", "Sie",
    "mein", "dein", "sein", "ihr", "unser", "euer", "Ihr",
    "dieser", "diese", "dieses", "jene", "jener", "jenes",
    "solcher", "solche", "solches", "derselbe", "dieselbe",
    "dasselbe", "derjenige", "diejenige", "dasjenige",
    "mich", "dich", "sich", "uns", "euch",
    "der", "die", "das", "welcher", "welche", "welches", "wer", "was",
    "wer", "was", "welcher", "welche", "welches", "wessen", "wem", "wen",
    "alle", "alles", "andere", "einer", "eine", "eines", "etliche",
    "etwas", "irgendein", "irgendwelche", "jeder", "jedes",
    "jemand", "kein", "keiner", "man", "mancher",
    "mehrere", "nichts", "niemand", "sämtliche",
    "viele", "wenige",
    "der", "die", "das", "ein", "eine", "einer", "kein", "keine",
    "selbst", "selber",
    "einander", "gegenseitig",
    "kein", "keiner", "niemand", "nichts",
    "alle", "einige", "etliche", "mehrere", "manche",
    "viel", "wenig", "sämtliche",
    "irgendein", "irgendjemand", "irgendwelche",
    "Sie", "Ihr",
    # Erweiterung
    "irgendwer", "irgendwas", "irgendwem", "irgendwen",
    "jeglicher", "jegliche", "jegliches",
    "manch", "mancherlei",
    "beiderlei", "beide",
    "solch", "welch",
    "irgendwer", "irgendwann", "irgendwo", "irgendwie",
    "niemandes",
    "deiner", "seiner", "ihrer", "unserer", "eurer",
    "wieviel", "wieviele", "wievieler",
    "desselben", "derselben",
    "was für ein", "was für welche",
    "solches", "dergleichen",
    "welcherlei",
    "dahin", "daher", "darum", "dafür",
    "wessen",
    "wer auch immer", "was auch immer",
    "jede/r/s", "irgendjemandes",
    "unsrige", "eurige", "seinige", "ihrige",
    "niemandem", "niemanden",
    "dortige", "hiesige", "hintere", "vordere"
]

verben = [
    "abholen", "abstimmen", "anfeuern", "anpacken", "anregen", "anknüpfen",
    "anstoßen", "antreiben", "auffangen", "auffordern", "aufklären", "aufleben",
    "auflösen", "aufmachen", "aufmischen", "aufnehmen", "aufrechterhalten",
    "aufstehen", "auftanken", "auftreten", "aufzeigen", "aufwecken",
    "aufwerten", "ausbauen", "ausbrechen", "ausgleichen", "ausleuchten",
    "ausprobieren", "ausrichten", "austauschen", "ausweiten", "auswirken",
    "beantworten", "begegnen", "begeistern", "begleiten", "begreifen",
    "behalten", "beherzigen", "beistehen", "bejahen", "bekennen",
    "bekräftigen", "bekämpfen", "belohnen", "bemühen", "benennen",
    "beobachten", "bequeren", "beraten", "berühren", "beschleunigen",
    "beschützen", "bestärken", "bestimmen", "betonen", "bewegen",
    "bewirken", "bewundern", "bilden", "brechen", "brückenbauen",
    "chancen schaffen", "denken", "durchbrechen", "durchdringen",
    "durchhalten", "durchstarten", "durchziehen", "einbringen",
    "einfordern", "einhaken", "einladen", "einleiten", "einmischen",
    "einordnen", "einprägen", "einstehen", "eintreten", "einverleiben",
    "einwirken", "empfinden", "empowern", "entdecken", "entfachen",
    "entfalten", "entkräften", "entlarven", "entlasten", "entwerfen",
    "entwickeln", "erfahren", "erfinden", "erfühlen", "erfüllen",
    "erhalten", "erheben", "erklären", "erleben", "erleuchten",
    "ermächtigen", "ermöglichen", "ermutigen", "erneuern", "erobern",
    "eröffnen", "erreichen", "erschaffen", "erschließen", "erschüttern",
    "erwägen", "erweitern", "erzählen", "etablieren", "experimentieren",
    "facilitieren", "fördern", "formen", "fragen", "freisetzen",
    "friedlich kämpfen", "fühlen", "füllen", "führen", "gedenken",
    "gegenhalten", "gegensteuern", "gemeinsam schaffen", "gestalten",
    "gewähren", "gewinnen", "gießen", "glänzen", "glühen",
    "greifen", "gründen", "grüßen", "handeln", "hervorbringen",
    "hervorrufen", "hineindenken", "hineinfühlen", "hineinversetzen",
    "hoffen", "hören", "impulse setzen", "in Bewegung bringen",
    "initiieren", "inspirieren", "intervenieren", "investieren",
    "kämpfen", "kanalisieren", "kapieren", "klarmachen", "klarstellen",
    "konsolidieren", "kooperieren", "kreieren", "kritisieren",
    "kultivieren", "lachen", "lagern", "lehren", "leiten",
    "leben", "leuchten", "lieben", "loben", "loslegen",
    "loslassen", "markieren", "mischen", "mobilisieren",
    "moderieren", "motivieren", "nachdenken", "nachgehen",
    "nachhaltig wirken", "nachrücken", "nachspüren", "nachvollziehen",
    "nachziehen", "nähern", "neu erfinden", "neu gestalten",
    "neu denken", "neu interpretieren", "neu starten",
    "nutzen", "offenbaren", "offenhalten", "offenlegen",
    "offenstehen", "optimieren", "organisieren", "orientieren",
    "partei ergreifen", "plädieren", "planen", "positionieren",
    "prägen", "präsentieren", "probieren", "projizieren",
    "provozieren", "realisieren", "rebellieren", "reflektieren",
    "reformieren", "reparieren", "repräsentieren", "respektieren",
    "retten", "revolutionieren", "riskieren", "rufen",
    "sanieren", "schaffen", "schätzen", "schildern",
    "schützen", "sehen", "sensibilisieren", "sichern",
    "signalisieren", "sortieren", "spenden", "spiegeln",
    "spüren", "stabilisieren", "staunen", "stehen",
    "steuern", "stimmen", "stoßen", "streiten",
    "stärken", "stützen", "suchen", "teilen",
    "tragen", "träumen", "treffen", "überdenken",
    "überfluten", "übergeben", "überleben", "überlegen",
    "überzeugen", "überwinden", "umarmen", "umdenken",
    "umgestalten", "umleiten", "umsetzen", "umwälzen",
    "unterstützen", "unterstreichen", "verbinden",
    "verbreiten", "verdeutlichen", "verehren",
    "verfechten", "verfolgen", "vergeben",
    "vergessen", "verknüpfen", "verlangen",
    "verleihen", "vermehren", "vermitteln",
    "vernichten", "verpflichten", "verstehen",
    "verstärken", "verteidigen", "verwirklichen",
    "verzahnen", "verzeihen", "voranbringen",
    "vorantreiben", "vorbereiten", "vorführen",
    "vorleben", "vorstellen", "vorwärtsgehen",
    "wachrütteln", "wagen", "warten",
    "weiterdenken", "weitergeben", "weitergehen",
    "weitertragen", "weiterwirken", "wertschätzen",
    "wirken", "wollen", "wunder schaffen",
    "zeigen", "zerlegen", "zerstreuen",
    "ziehen", "zuhören", "zupacken",
    "zurückblicken", "zurückfinden", "zurückgewinnen",
    "zurückholen", "zusammenarbeiten", "zusammenbringen",
    "zusammenfinden", "zusammenhalten", "zusammenkommen",
    "zusammenrücken", "zusammentragen", "zusammenwirken"
]

adjektive = [
    "abenteuerlustig", "achtsam", "aktiv", "attraktiv", "authentisch",
    "aufgeschlossen", "ausgeglichen", "ausdauernd", "beeindruckend",
    "begeisterungsfähig", "beliebt", "bemerkenswert", "berührend",
    "bescheiden", "besonnen", "bedeutend", "bezahlbar",
    "charismatisch", "charmant", "clever", "cool", "dankbar",
    "dynamisch", "effektiv", "ehrlich", "einfühlsam",
    "einzigartig", "elegant", "eloquent", "empathisch",
    "energetisch", "engagiert", "erfinderisch", "erfolgreich",
    "erholsam", "ernsthaft", "erstaunlich", "fachkundig",
    "fair", "fantasievoll", "fleißig", "flexibel",
    "freundlich", "fröhlich", "friedlich", "geduldig",
    "geeignet", "geistreich", "gekonnt", "gemeinschaftlich",
    "genau", "genial", "gerecht", "gesund", "glücklich",
    "großzügig", "harmonisch", "herzlich", "hilfsbereit",
    "hoffnungsvoll", "intelligent", "interessant",
    "innovativ", "intensiv", "jung", "kameradschaftlich",
    "kämpferisch", "klar", "klug", "kompetent",
    "konsequent", "kreativ", "kräftig", "kulturell",
    "lebendig", "leidenschaftlich", "lernfähig",
    "liebenswürdig", "logisch", "loyal", "mächtig",
    "maßgeblich", "menschenfreundlich", "modern", "motiviert",
    "mutig", "nachhaltig", "nachsichtig", "natürlich",
    "neugierig", "offen", "optimistisch", "organisiert",
    "partnerschaftlich", "passioniert", "persönlich",
    "phantasievoll", "pünktlich", "qualifiziert",
    "raffiniert", "respektvoll", "risikobereit",
    "romantisch", "sanft", "scharfsinnig", "schnell",
    "schöpferisch", "selbstbewusst", "selbstständig",
    "sicher", "simpel", "sinnvoll", "solidarisch",
    "sozial", "spontan", "sportlich", "stark",
    "sympathisch", "taktvoll", "teamfähig", "temperamentvoll",
    "tiefgründig", "tolerant", "transparent", "treu",
    "überzeugend", "umfassend", "umweltbewusst", "unabhängig",
    "unaufdringlich", "uneigennützig", "unerschütterlich",
    "universell", "verantwortungsbewusst", "verlässlich",
    "vertrauensvoll", "vielseitig", "visionär",
    "vorbildlich", "warmherzig", "weitsichtig",
    "wertvoll", "widerstandsfähig", "willensstark",
    "wirkungsvoll", "wunderbar", "zielgerichtet",
    "zielstrebig", "zuverlässig", "zuvorkommend",
    "allgemein", "alt", "angemessen", "anpassungsfähig",
    "arm", "auffällig", "ausdrücklich", "automatisch",
    "bekannt", "beschreibend", "deutlich", "direkt",
    "durchschnittlich", "effizient", "eindeutig",
    "einfach", "ernst", "erprobt", "erwartbar",
    "existent", "extern", "formell", "funktional",
    "gleichmäßig", "grundsätzlich", "häufig",
    "hochwertig", "ideell", "indirekt", "intern",
    "klassisch", "kurz", "lang", "leicht",
    "logisch", "mittelgroß", "möglich",
    "naheliegend", "nebenstehend", "neutral",
    "objektiv", "offensichtlich", "praktisch",
    "pragmatisch", "regelmäßig", "relevant",
    "reproduzierbar", "robust", "rund",
    "sachlich", "scheinbar", "sichtbar",
    "standardisiert", "systematisch", "technisch",
    "theoretisch", "typisch", "unauffällig",
    "unabhängig", "verständlich", "vertikal",
    "vollständig", "wahrscheinlich", "wesentlich",
    "wirtschaftlich", "zeitlos", "zufällig",
    "abgehoben", "aggressiv", "altmodisch", "ängstlich",
    "anmaßend", "arrogant", "bedrohlich", "befangen",
    "befremdlich", "beklommen", "belastend",
    "beschränkt", "bitter", "chaotisch",
    "düster", "egoistisch", "eigensinnig",
    "einseitig", "engstirnig", "enttäuschend",
    "erbärmlich", "erschreckend", "fatal",
    "feige", "fehlgeschlagen", "feindselig",
    "fremd", "gefährlich", "gehässig",
    "gelangweilt", "gemein", "genervt",
    "geschmacklos", "gleichgültig", "grausam",
    "griesgrämig", "hart", "heuchlerisch",
    "hinterlistig", "hitzköpfig", "horrend",
    "hysterisch", "ignorant", "illoyal",
    "inkonsequent", "irrational", "kaltherzig",
    "kleinkariert", "kompliziert", "krankhaft",
    "kränkend", "kritikwürdig", "kurzsichtig",
    "lahm", "langweilig", "lügnerisch",
    "lustlos", "mangelhaft", "melancholisch",
    "mies", "misstrauisch", "nachtragend",
    "niederträchtig", "oberflächlich", "ohnegleichen",
    "pessimistisch", "peinlich", "planlos",
    "problematisch", "provozierend", "rücksichtslos",
    "rüpelhaft", "schadenfroh", "scheu",
    "schlampig", "schrecklich", "selbstgerecht",
    "sensationslüstern", "skandalös", "snobistisch",
    "sorglos", "spießig", "starrköpfig",
    "stumpfsinnig", "stur", "tadelnswert",
    "taktlos", "träumerisch", "trotzig",
    "überheblich", "übertrieben", "unaufrichtig",
    "unangenehm", "unberechenbar", "unbeständig",
    "undankbar", "unerträglich", "ungeduldig",
    "unhöflich", "uninteressant", "unkreativ",
    "unmoralisch", "unnütz", "unordentlich",
    "unruhig", "unsicher", "unsympathisch",
    "untätig", "unverbindlich", "unwichtig",
    "unzufrieden", "verärgert", "verbohrt",
    "verlogen", "verschwenderisch", "verstört",
    "verwirrt", "verwundet", "vorlaut",
    "widersprüchlich", "widerwärtig", "wütend",
    "zynisch"
]

artikel = [
    "der", "die", "das",
    "des", "deren", "dessen",
    "dem", "den",
    "diejenigen", "derselbe", "dieselbe", "dasselbe",
    "jener", "jene", "jenes",
    "ein", "eine", "einer",
    "eines", "einem", "einen",
    "kein", "keine", "keiner",
    "keines", "keinem", "keinen",
    "am", "ans", "im", "ins", "zum",
    "zur", "vom", "aufs",
    "überm", "unterm", "vorm", "hinterm",
    "solch", "solche", "solches",
    "manch", "manche", "manches",
    "welch", "welche", "welches",
    "all", "alle",
    "jeder", "jede", "jedes",
    "beide", "beider", "beides"
]

praepositionen = [
    # Präpositionen mit dem Akkusativ
    "bis", "durch", "entlang", "für", "gegen",
    "ohne", "um", "wider",

    # Präpositionen mit dem Dativ
    "ab", "aus", "außer", "bei", "dank",
    "gegenüber", "gemäß", "mit", "nach",
    "seit", "von", "zu", "zufolge",

    # Präpositionen mit dem Genitiv
    "anstatt", "außerhalb", "innerhalb",
    "infolge", "jenseits", "kraft", "längs",
    "laut", "oberhalb", "statt", "trotz",
    "ungeachtet", "unterhalb", "während", "wegen",
    "zwecks",

    # Wechselpräpositionen (Dativ oder Akkusativ, je nach Kontext)
    "an", "auf", "hinter", "in", "neben",
    "über", "unter", "vor", "zwischen",

    # Präpositionen des Ortes (lokal)
    "abseits", "abwärts", "aufwärts",
    "außerhalb", "diesseits", "entlang",
    "fernab", "hinter", "innerhalb",
    "jenseits", "links", "mittig",
    "nahe", "neben", "oberhalb",
    "rechts", "unterhalb", "vorbei",
    "zwischen",

    # Präpositionen der Zeit (temporal)
    "ab", "an", "binnen", "gegen",
    "innerhalb", "seit", "über", "um",
    "unter", "vor", "während", "zu",

    # Präpositionen der Art und Weise (modal)
    "anstelle", "auf", "aus", "durch",
    "mit", "ohne", "per", "pro",
    "statt", "via",

    # Präpositionen des Grundes (kausal)
    "angesichts", "anlässlich", "aufgrund",
    "dank", "infolge", "kraft",
    "mangels", "trotz", "wegen",
    "zwecks",

    # Präpositionen der Richtung (direktional)
    "ab", "an", "auf", "entlang",
    "gen", "nach", "über",
    "um", "unter", "vor", "zu",

    # Präpositionen der Zugehörigkeit (relational)
    "angesichts", "anhand", "aufseiten",
    "bezüglich", "inmitten", "seitens",

    # Präpositionen des Vergleichs (komparativ)
    "anstatt", "dank", "gleich",
    "jenseits", "längs", "neben",

    # Zusammengesetzte Präpositionen
    "abseits von", "abzüglich", "anlässlich",
    "anstelle von", "aufgrund von",
    "im Falle von", "in Bezug auf",
    "inmitten von", "mithilfe von",
    "mitten in", "ungeachtet von",
    "unter Berücksichtigung", "im Gegensatz zu",

    # Umgangssprachliche Präpositionen
    "außer", "ohne", "pro",
    "via", "per",

    # Präpositionen in festen Wendungen
    "auf Achse", "auf Reisen",
    "bei Tag", "bei Nacht",
    "in Eile", "in Kürze",
    "unter Druck", "zu Besuch"
]

konjunktionen = [
    # Nebenordnende Konjunktionen (koordinierende Konjunktionen)
    "aber", "allein", "also",
    "andererseits", "außerdem", "bald",
    "beziehungsweise", "bloß", "denn",
    "doch", "einerseits", "entweder",
    "ferner", "folglich", "gleichwohl",
    "indessen", "jedoch", "mal",
    "nur", "oder", "respektive",
    "schließlich", "sobald", "sodass",
    "sondern", "sowie", "stattdessen",
    "trotzdem", "und", "vielmehr",
    "weder", "zudem", "zwar",

    # Unterordnende Konjunktionen (subordinierende Konjunktionen)
    "als", "als ob", "anstatt dass",
    "auch wenn", "außer dass", "bevor",
    "bis", "da", "dabei",
    "dadurch dass", "dass", "demnach",
    "denn", "deshalb", "deswegen",
    "ehe", "falls", "gleichfalls",
    "gleichsam", "gleichzeitig", "indem",
    "insofern", "insoweit", "je",
    "je nachdem", "nachdem", "ob",
    "obgleich", "obschon", "obwohl",
    "ohne dass", "seit", "seitdem",
    "sobald", "sofern", "solange",
    "soweit", "statt dass", "während",
    "weil", "wenn", "wenngleich",
    "wiewohl", "wo", "wobei",
    "wofür", "wohingegen", "wozu",

    # Doppelkonjunktionen (korrelative Konjunktionen)
    "entweder ... oder",
    "weder ... noch",
    "sowohl ... als auch",
    "nicht nur ... sondern auch",
    "je ... desto",
    "einerseits ... andererseits",
    "ob ... oder",
    "teils ... teils",
    "so ... wie",
    "umso ... je",

    # Konjunktionen zur Angabe von Gründen (kausale Konjunktionen)
    "da", "weil", "zumal", "daher", "deshalb",
    "aus diesem Grund", "infolgedessen", "weshalb", "warum",

    # Konjunktionen zur Zeitangabe (temporale Konjunktionen)
    "als", "ehe", "nachdem", "seit",
    "seitdem", "sobald", "solange", "während", "bis",

    # Konjunktionen zur Angabe eines Zwecks (finale Konjunktionen)
    "damit", "dazu", "um ... zu",
    "auf dass",

    # Konjunktionen zur Angabe einer Bedingung (konditionale Konjunktionen)
    "falls", "sofern", "wenn", "vorausgesetzt",
    "es sei denn", "unter der Voraussetzung",

    # Konjunktionen zur Angabe einer Folge (konsekutive Konjunktionen)
    "sodass", "so ... dass", "daher",
    "folglich", "infolgedessen",

    # Konjunktionen zur Angabe eines Gegensatzes (adversative Konjunktionen)
    "aber", "allein", "doch",
    "jedoch", "hingegen", "stattdessen",
    "während", "obgleich", "obwohl",
    "wenngleich", "gleichwohl",

    # Konjunktionen zur Angabe eines Vergleichs (komparative Konjunktionen)
    "als", "als ob", "als wenn",
    "wie", "genauso wie", "so wie",
    "je", "desto", "umso", "je",

    # Konjunktionen zur Einschränkung (konzessive Konjunktionen)
    "obgleich", "obschon", "obwohl",
    "wenngleich", "trotzdem", "gleichwohl",
    "ungeachtet dessen",

    # Konjunktionen zur Begründung oder Erklärung (explikative Konjunktionen)
    "nämlich", "und zwar",
    "das heißt",
    "mit anderen Worten",

    # Konjunktionen zur Wahlmöglichkeit (disjunktive Konjunktionen)
    "entweder",
    "ob", "oder",
    "sei es", "sei es",
    "weder", "noch"
]

numerale = [
    # Kardinalzahlen (Grundzahlen)
    "null", "eins", "zwei", "drei", "vier", "fünf",
    "sechs", "sieben", "acht", "neun", "zehn",
    "elf", "zwölf", "dreizehn", "vierzehn",
    "fünfzehn", "sechzehn", "siebzehn",
    "achtzehn", "neunzehn", "zwanzig",
    "einundzwanzig", "zweiundzwanzig", "dreißig",
    "vierzig", "fünfzig", "sechzig", "siebzig",
    "achtzig", "neunzig", "hundert", "tausend",
    "zehntausend", "hunderttausend",
    "eine Million", "eine Milliarde",
    "eine Billion", "eine Billiarde",

    # Ordinalzahlen (Ordnungszahlen)
    "erste", "zweite", "dritte", "vierte",
    "fünfte", "sechste", "siebte",
    "achte", "neunte", "zehnte",
    "elfte", "zwölfte", "dreizehnte",
    "zwanzigste", "einundzwanzigste",
    "dreißigste", "vierzigste",
    "hundertste", "tausendste",

    # Bruchzahlen (Partitivzahlen)
    "halb", "viertel", "drittel",
    "fünftel", "sechstel", "siebtel",
    "achtel", "neuntel", "zehntel",
    "hundertstel", "tausendstel",

    # Vervielfältigungszahlen (Multiplikative Numeralien)
    "einfach", "zweifach", "dreifach",
    "vierfach", "fünffach", "sechsfach",
    "mehrfach", "vielfach",

    # Verteilungszahlen (Distributive Numeralien)
    "je eins", "je zwei", "je drei",
    "jeweils", "zu zweit", "zu dritt",
    "paarweise", "dutzendweise",

    # Kollektivzahlen (Sammelzahlen)
    "beide", "alle", "ein paar",
    "einige", "mehrere", "dutzend",
    "hunderte", "tausende",

    # Unbestimmte Zahlwörter (Indefinitnumeralien)
    "wenige", "viele", "manche",
    "mehrere", "etliche",
    "unzählige", "unendlich",
    "zahlreiche", "hunderte", "tausende",

    # Zahlenadverbien
    "einmal", "zweimal", "dreimal",
    "viermal", "fünfmal",
    "mehrmals", "vielmals",
    "einzig", "erstmals",
    "letztmals", "abermals"
]

interjektionen = [
    # Interjektionen zur Begrüßung und Verabschiedung
    "hallo", "hi", "hey",
    "servus", "moin", "grüß dich",
    "tschüss", "ciao", "ade",
    "leb wohl", "bis bald", "auf Wiedersehen",

    # Interjektionen der Zustimmung und Bestätigung
    "ja", "jawohl", "genau",
    "freilich", "sicher",
    "stimmt", "natürlich",
    "klar", "einverstanden",

    # Interjektionen der Verneinung oder Ablehnung
    "nein", "nö", "niemals",
    "doch nicht", "auf keinen Fall",

    # Interjektionen des Erstaunens und der Überraschung
    "oh", "aha", "oho",
    "ach", "wow", "huch",
    "na sowas", "echt?",
    "krass", "unglaublich!",
    "ui", "ups", "uff",

    # Interjektionen des Bedauerns und Mitgefühls
    "ach", "oje", "oh je",
    "oh nein", "schade",
    "tja", "seufz",
    "hmm", "leider",

    # Interjektionen des Ekels und der Abneigung
    "pfui", "ih", "bäh",
    "igitt", "würg",
    "pah", "bah",

    # Interjektionen der Freude und des Jubels
    "hurra", "juhu", "yay",
    "wow", "yeah", "yippie",
    "hossa", "bravo", "ole",
    "klasse", "super",
    "spitze", "genial",

    # Interjektionen der Ermunterung und Motivation
    "los", "auf geht’s",
    "hopp", "hoppala",
    "mach schon", "vorwärts",
    "weiter so", "nur zu!",
    "komm schon", "gib Gas!",
    "pack’s an",

    # Interjektionen der Warnung und des Schreckens
    "vorsicht", "halt", "stopp",
    "aufpassen", "achtung",
    "aua", "oh weh",
    "hilfe", "weg da!",
    "um Himmels willen!",
    "um Gottes willen!",
    "verdammt!", "zum Teufel!",

    # Interjektionen des Zögerns und Nachdenkens
    "äh", "hm", "hmm",
    "tja", "nun ja",
    "mh", "öhm",
    "hmmja",

    # Interjektionen des Spottes und der Ironie
    "ha", "haha", "hihi",
    "hoho", "pff", "tsss",
    "na klar!", "witzig!",
    "sehr lustig!", "jaja...",

    # Tierlaut-Imitationen (onomatopoetische Interjektionen)
    "wau", "miau", "kikeriki",
    "quak", "muh", "piep",
    "brumm", "zirp", "gurr",
    "klirr", "platsch", "krach",

    # Geräusch-Imitationen (Lautmalerei/Onomatopoesie)
    "bumm", "peng", "zack",
    "plopp", "klirr",
    "puff", "rums",
    "klack", "schnapp",
    "bäng", "ratsch"
]

words = [
    nomen + adverbien + pronomen + verben + adjektive + artikel + praepositionen + konjunktionen + numerale + interjektionen]
